import 'package:grocery_app/Models/item_model.dart';

final Map<String, List<Item>> categoryItems = {
  'Fruits': [
    Item(
      title: 'Apple',
      price: '₹ 60.00',
      imagePath: 'assets/dummyimage/apple.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
    Item(
      title: 'Banana',
      price: '₹ 45.00',
      imagePath: 'assets/dummyimage/banana.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
    Item(
      title: 'Mango',
      price: '₹ 65.00',
      imagePath: 'assets/dummyimage/mango.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
    Item(
      title: 'Orange',
      price: '₹ 50.00',
      imagePath: 'assets/carousal_images/orange.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
    Item(
      title: 'Strawberry',
      price: '₹ 200.00',
      imagePath: 'assets/dummyimage/strawberry.png',
      imageHeight: 60,
      weight: '250gm',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
    Item(
      title: 'Avacado',
      price: '₹ 200.00',
      imagePath: 'assets/dummyimage/avacado.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
    Item(
      title: 'Guava',
      price: '₹ 70.00',
      imagePath: 'assets/dummyimage/fruits/guava.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
    Item(
      title: 'Pappaya',
      price: '₹ 80.00',
      imagePath: 'assets/dummyimage/fruits/papaya.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
    Item(
      title: 'Pineapple',
      price: '₹ 40.00',
      imagePath: 'assets/dummyimage/fruits/pineapple.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
    Item(
      title: 'Grapes',
      price: '₹ 50.00',
      imagePath: 'assets/dummyimage/fruits/grapes.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Fresh and juicy fruits packed with vitamins, minerals, and natural sweetness. Perfect for a healthy lifestyle and everyday snacking.',
    ),
  ],
  'Vegetables': [
    Item(
      title: 'Carrot',
      price: '₹ 30.00',
      imagePath: 'assets/dummyimage/carrot.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
    Item(
      title: 'Onion',
      price: '₹ 50.00',
      imagePath: 'assets/dummyimage/onion.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
    Item(
      title: 'Cabbage',
      price: '₹ 30.00',
      imagePath: 'assets/dummyimage/cabbage.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
    Item(
      title: 'Tomato',
      price: '₹ 25.00',
      imagePath: 'assets/carousal_images/tomato.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
    Item(
      title: 'Ginger',
      price: '₹ 40.00',
      imagePath: 'assets/dummyimage/ginger.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
    Item(
      title: 'Capsicum',
      price: '₹ 50.00',
      imagePath: 'assets/dummyimage/capsicum.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
    Item(
      title: 'Potato',
      price: '₹ 30.00',
      imagePath: 'assets/dummyimage/vegs/potato.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
    Item(
      title: 'Beetroot',
      price: '₹ 40.00',
      imagePath: 'assets/dummyimage/vegs/beetroot.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
    Item(
      title: 'Cucumber',
      price: '₹ 30.00',
      imagePath: 'assets/dummyimage/vegs/cucumber.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
    Item(
      title: 'Brinjal',
      price: '₹ 45.00',
      imagePath: 'assets/dummyimage/vegs/brinjal.png',
      imageHeight: 60,
      weight: '1kg',
      description:
          'Green and  leafy, fresh vegetables rich in nutrients and fiber. Essential for cooking delicious and healthy meals.',
    ),
  ],
  'Dairy': [
    Item(
      title: 'Milk',
      price: '₹ 50',
      imagePath: 'assets/dummyimage/milk.png',
      imageHeight: 60,
      weight: '1ltr',
    ),
    Item(
      title: 'Cheese',
      price: '₹ 120',
      imagePath: 'assets/dummyimage/cheese.png',
      imageHeight: 60,
      weight: '100gm',
    ),
    Item(
      title: 'Butter',
      price: '₹ 150',
      imagePath: 'assets/dummyimage/butter.png',
      imageHeight: 60,
      weight: '100gm',
    ),
    Item(
      title: 'Paneer',
      price: '₹ 20',
      imagePath: 'assets/dummyimage/paneer.png',
      imageHeight: 60,
      weight: '100gm',
    ),
    Item(
      title: 'Curd',
      price: '₹ 25',
      imagePath: 'assets/dummyimage/curd.png',
      imageHeight: 60,
      weight: '1',
    ),
    Item(
      title: 'Yogurt',
      price: '₹ 30',
      imagePath: 'assets/dummyimage/yogurt.png',
      imageHeight: 60,
      weight: '1',
    ),
  ],
  'Bakery': [
    Item(
      title: 'Bread',
      price: '₹ 50',
      imagePath: 'assets/Items/bakes.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Biscuite',
      price: '₹ 50',
      imagePath: 'assets/Items/bakes.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Bun',
      price: '₹ 50',
      imagePath: 'assets/Items/bakes.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Donut',
      price: '₹ 50',
      imagePath: 'assets/Items/bakes.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Cupcake',
      price: '₹ 50',
      imagePath: 'assets/Items/bakes.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Brownie',
      price: '₹ 50',
      imagePath: 'assets/Items/bakes.png',
      imageHeight: 60,
      weight: '1kg',
    ),
  ],
  'Grains': [
    Item(
      title: 'Rice',
      price: '₹ 50',
      imagePath: 'assets/Items/grains.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Wheat',
      price: '₹ 50',
      imagePath: 'assets/Items/grains.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Barley',
      price: '₹ 50',
      imagePath: 'assets/Items/grains.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Oats',
      price: '₹ 50',
      imagePath: 'assets/Items/grains.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Millet',
      price: '₹ 50',
      imagePath: 'assets/Items/grains.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Bajra',
      price: '₹ 50',
      imagePath: 'assets/Items/grains.png',
      imageHeight: 60,
      weight: '1kg',
    ),
  ],
  'Snacks': [
    Item(
      title: 'Chips',
      price: '₹ 50',
      imagePath: 'assets/Items/snacks.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Popcorn',
      price: '₹ 50',
      imagePath: 'assets/Items/snacks.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Cookies',
      price: '₹ 50',
      imagePath: 'assets/Items/snacks.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Chocolate Bar',
      price: '₹ 50',
      imagePath: 'assets/Items/snacks.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Mixture',
      price: '₹ 50',
      imagePath: 'assets/Items/snacks.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Lays',
      price: '₹ 50',
      imagePath: 'assets/Items/snacks.png',
      imageHeight: 60,
      weight: '1kg',
    ),
  ],
  'Spices': [
    Item(
      title: 'Turmeric',
      price: '₹ 50',
      imagePath: 'assets/Items/spice.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Chilly powder',
      price: '₹ 50',
      imagePath: 'assets/Items/spice.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Black pepper',
      price: '₹ 50',
      imagePath: 'assets/Items/spice.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Cinnamon',
      price: '₹ 50',
      imagePath: 'assets/Items/spice.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Cloves',
      price: '₹ 50',
      imagePath: 'assets/Items/spice.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Garam Masala',
      price: '₹ 50',
      imagePath: 'assets/Items/spice.png',
      imageHeight: 60,
      weight: '1kg',
    ),
  ],
  'Beverages': [
    Item(
      title: 'Lassi',
      price: '₹ 50',
      imagePath: 'assets/Items/beverage.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Fruit Juices',
      price: '₹ 50',
      imagePath: 'assets/Items/beverage.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Soft Drinks',
      price: '₹ 50',
      imagePath: 'assets/Items/beverage.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Buttermilk',
      price: '₹ 50',
      imagePath: 'assets/Items/beverage.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Soda Water',
      price: '₹ 50',
      imagePath: 'assets/Items/beverage.png',
      imageHeight: 60,
      weight: '1kg',
    ),
    Item(
      title: 'Mineral Water',
      price: '₹ 50',
      imagePath: 'assets/Items/beverage.png',
      imageHeight: 60,
      weight: '1kg',
    ),
  ],
};
